version: "3.7"

services:
  web:
    container_name: oracle
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: run
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - 8005:8005
    links:
      - db
    depends_on:
      - db



  db:
    container_name: postgres
    restart: always
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      .env
    ports:
      - 5435:5432


volumes:
  postgres-data: